%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "Rectified"

# Rectified Camera calibration (OpenCV)
Camera1.fx: 7.7537235550066748e+02
Camera1.fy: 7.7537235550066748e+02
Camera1.cx: 6.1947309112548828e+02
Camera1.cy: 2.5718049049377441e+02

Stereo.b: 0.475

# Camera resolution
Camera.width: 1280
Camera.height: 560

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.006808248599665321, -0.999976568263188, -0.0004389831010508009, 0.1892723999026909,
          -0.015328813180564112, 0.00033478416677165885, -1.0003517895427012, 1.6097603368744715,
          1.0003385811346779, -0.006810981590115021, 0.015326201598105391, 0.0344605721730176,
          0.0, 0.0, 0.0, 1.0]

   # data: [-0.006808248599665321061, -0.99997656826318804748, -0.00043898310105080090182, 0.259272399902690897,
   #        -0.015328813180564113, 0.00033478416677165885, -1.0003517895427011348, 1.6097603368744715,
   #        1.0003385811346779782, -0.0068109815901150212555, 0.015326201598105391556, -1.66553942782698245,
   #        0.0, 0.0, 0.0, 1.0]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise
IMU.NoiseGyro: 0.000175 # 1.6968e-04 
IMU.NoiseAcc: 0.000589 # 2.0000e-3
IMU.GyroWalk: 0.0000485 
IMU.AccWalk: 0.000147 # 3.0000e-3
IMU.Frequency: 100.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
